/* Build a large bank of Shikaku puzzles with GUARANTEED UNIQUE solutions.

   Pipeline:
   1. generatePuzzle() builds a random full rectangle tiling, then drops one
      clue per rectangle  -> always solvable, but maybe not uniquely.
   2. A backtracking exact-cover solver counts solutions (stops at 2).
   3. Keep only puzzles with exactly one solution; dedupe by serialized grid.
   4. Collect a target number per grid size and emit js/levels.js.

   Run: node tools/genbank.js
*/
const fs = require('fs');
global.window = {};
require('../js/puzzle.js');
const { generatePuzzle } = global.window.SHIKAKU_PUZZLE;

// Enumerate every rectangle that covers clue (cr,cc,val): area==val, contains
// exactly that one clue.
function candidatesFor(g, N, cr, cc, val) {
  const out = [];
  for (let h = 1; h <= val; h++) {
    if (val % h) continue;
    const w = val / h;
    if (h > N || w > N) continue;
    for (let r0 = Math.max(0, cr - h + 1); r0 <= cr && r0 + h <= N; r0++) {
      for (let c0 = Math.max(0, cc - w + 1); c0 <= cc && c0 + w <= N; c0++) {
        const r1 = r0 + h - 1, c1 = c0 + w - 1;
        let clues = 0;
        for (let r = r0; r <= r1; r++) for (let c = c0; c <= c1; c++) if (g[r][c] > 0) clues++;
        if (clues === 1) out.push({ r0, c0, r1, c1 });
      }
    }
  }
  return out;
}

// Count solutions up to `cap` (2 = "is it unique?").
function countSolutions(g, N, cap = 2) {
  const clues = [];
  for (let r = 0; r < N; r++) for (let c = 0; c < N; c++) if (g[r][c] > 0) clues.push({ r, c, v: g[r][c] });
  if (clues.reduce((a, x) => a + x.v, 0) !== N * N) return 0;
  const cand = clues.map(cl => candidatesFor(g, N, cl.r, cl.c, cl.v));
  if (cand.some(list => list.length === 0)) return 0;

  const cover = Array.from({ length: N }, () => Array(N).fill(false));
  const used = new Array(clues.length).fill(false);
  const fits = rc => { for (let r = rc.r0; r <= rc.r1; r++) for (let c = rc.c0; c <= rc.c1; c++) if (cover[r][c]) return false; return true; };
  const mark = (rc, v) => { for (let r = rc.r0; r <= rc.r1; r++) for (let c = rc.c0; c <= rc.c1; c++) cover[r][c] = v; };
  const firstEmpty = () => { for (let r = 0; r < N; r++) for (let c = 0; c < N; c++) if (!cover[r][c]) return [r, c]; return null; };

  let found = 0;
  (function bt() {
    if (found >= cap) return;
    const e = firstEmpty();
    if (!e) { found++; return; }
    const [er, ec] = e;
    // which clue-rectangles could cover this empty cell?
    for (let i = 0; i < clues.length; i++) {
      if (used[i]) continue;
      for (const rc of cand[i]) {
        if (er >= rc.r0 && er <= rc.r1 && ec >= rc.c0 && ec <= rc.c1 && fits(rc)) {
          used[i] = true; mark(rc, true);
          bt();
          mark(rc, false); used[i] = false;
          if (found >= cap) return;
        }
      }
    }
  })();
  return found;
}

const key = g => g.map(r => r.join('')).join('|');
const clueCount = g => g.reduce((a, r) => a + r.filter(v => v > 0).length, 0);

// Per-size config: how many unique templates we want, and clue-density window.
const SIZES = [
  { N: 4, want: 24, maxArea: 4, lo: 4, hi: 8 },
  { N: 5, want: 30, maxArea: 6, lo: 5, hi: 11 },
  { N: 6, want: 30, maxArea: 8, lo: 6, hi: 14 },
  { N: 7, want: 24, maxArea: 9, lo: 8, hi: 18 },
];

const bank = {};
let totalChecked = 0, totalUnique = 0;

for (const cfg of SIZES) {
  const seen = new Set();
  const pool = [];
  let seed = 1;
  const limit = 400000;
  while (pool.length < cfg.want && seed < limit) {
    const { g } = generatePuzzle(cfg.N, seed++, cfg.maxArea);
    totalChecked++;
    const cc = clueCount(g);
    if (cc < cfg.lo || cc > cfg.hi) continue;
    const k = key(g);
    if (seen.has(k)) continue;
    if (countSolutions(g, cfg.N, 2) !== 1) continue;
    seen.add(k);
    pool.push(g);
    totalUnique++;
  }
  bank[cfg.N] = pool;
  console.log(`N=${cfg.N}: ${pool.length}/${cfg.want} unique templates (seeds tried up to ${seed})`);
}

const total = Object.values(bank).reduce((a, p) => a + p.length, 0);
if (total < 100) { console.error(`Only ${total} templates — need >= 100`); process.exit(1); }

// Emit js/levels.js
const ser = bank => Object.entries(bank).map(([N, pool]) =>
  `  "${N}": [\n${pool.map(g => '    ' + JSON.stringify(g)).join(',\n')}\n  ]`
).join(',\n');

const out = `/* ============================================================================
   Shikaku level bank — ${total} puzzles with GUARANTEED UNIQUE solutions.

   AUTO-GENERATED by tools/genbank.js. Do not edit by hand.
   Keyed by grid size; each entry is an N×N grid (0 = empty, k>0 = clue of area k).
   Every board was verified to have exactly one solution by an exact-cover solver.
   The quest draws a fresh random template (by size) on each play.
   ============================================================================ */
window.SHIKAKU_LEVELS = {
${ser(bank)}
};
`;
fs.writeFileSync(__dirname + '/../js/levels.js', out);
console.log(`\nWrote js/levels.js with ${total} unique templates (checked ${totalChecked}, unique ${totalUnique}).`);
